# Generated by Django 4.2.7 on 2026-04-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_tracking_token"),
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="orders.order",
            ),
        ),
    ]
