# Generated by Django 5.2.17 on 2026-08-29 02:25

import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_review_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="customer_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="reviews/",
                validators=[marketing.models.validate_review_photo_size],
            ),
        ),
    ]
