# Generated by Django 6.1 on 2026-08-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_alter_review_customer_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"ordering": ["code"]},
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={"ordering": ["-starts_at"]},
        ),
    ]
