# Generated by Django 5.2.17 on 2026-08-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name_plural": "categories",
            },
        ),
    ]
