# Generated by Django 6.1 on 2026-08-30 16:52

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="menu/",
                validators=[menu.models.validate_menu_image_size],
            ),
        ),
    ]
