# Generated by Django 4.2.7 on 2026-04-05 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
