# Generated by Django 6.1 on 2026-08-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not required"),
                    ("pending", "Pending payment"),
                    ("paid", "Paid"),
                    ("failed", "Payment failed"),
                    ("refunded", "Refunded"),
                ],
                default="not_required",
                max_length=20,
            ),
        ),
    ]
