# Generated by Django 6.1 on 2026-08-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryzone",
            options={"ordering": ["name"]},
        ),
    ]
