# Generated by Django 6.1 on 2026-08-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_deliveryzone_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="guest_delivery_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_delivery_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_delivery_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_delivery_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_delivery_postal_code",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_delivery_state",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
